name: OpenFL air

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.3.4
    - uses: joshtynjala/setup-adobe-air-action@v2
      with:
        air-version: "33.1"
        accept-license: true
    - name: Set up Haxelib dependencies
      run: |
        haxelib install lime --quiet
        haxelib install openfl --quiet
        haxelib run lime config AIR_SDK ${{ env.AIR_HOME }}
    - name: Build project
      run: |
        haxelib run openfl build air
