name: OpenFL mac

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.3.4
    - name: Set up Haxelib dependencies
      run: |
        haxelib install lime --quiet
        haxelib install openfl --quiet
        haxelib install hxcpp --quiet
    - name: Build project
      run: |
        haxelib run openfl build mac
