name: OpenFL ios

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.1.2
    - name: Set up Haxelib dependencies
      run: |
        haxelib install lime --quiet
        haxelib install openfl --quiet
        haxelib install hxcpp --quiet
    - name: Build project
      run: |
        haxelib run openfl build ios -simulator
