name: OpenFL android

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: nttld/setup-ndk@v1
      id: setup-ndk 
      with:
        ndk-version: r15c
    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.2.5
    - name: Set up Haxelib dependencies
      run: |
        haxelib install lime --quiet
        haxelib install openfl --quiet
        haxelib install hxcpp 4.2.1 --quiet
    - uses: actions/setup-java@v4
      with:
        java-version: "11"
        distribution: "temurin"
    - name: lime setup android
      run: |
        haxelib run lime config ANDROID_SDK $ANDROID_SDK_ROOT
        haxelib run lime config ANDROID_NDK_ROOT ${{ steps.setup-ndk.outputs.ndk-path }}
        haxelib run lime config JAVA_HOME ${{ env.JAVA_HOME }}
        haxelib run lime config ANDROID_SETUP true
        haxelib run lime config
    - name: Build project
      run: |
        haxelib run openfl build android
