name: OpenFL android

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      ANDROID_NDK_ROOT: /opt/android-ndk-r15c

    steps:
    - uses: actions/checkout@v3
    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.1.2
    - name: Set up Haxelib dependencies
      run: |
        haxelib install lime --quiet
        haxelib install openfl --quiet
        haxelib install hxcpp --quiet
    - uses: actions/setup-java@v3
      with:
        java-version: "8"
        distribution: "temurin"
    - name: Set up Android NDK r15c
      run: |
        mkdir $ANDROID_NDK_ROOT
        wget -O android-ndk.zip --quiet https://dl.google.com/android/repository/android-ndk-r15c-linux-x86_64.zip
        unzip -qq android-ndk.zip -d $ANDROID_NDK_ROOT/..
        rm android-ndk.zip
    - name: lime setup android
      run: |
        haxelib run lime config ANDROID_SDK $ANDROID_HOME
        haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_ROOT
        haxelib run lime config JAVA_HOME $JAVA_HOME
        haxelib run lime config ANDROID_SETUP true
        haxelib run lime config
    - name: Build project
      run: |
        haxelib run openfl build android
